### PR TITLE
Update project.lektorproject

### PR DESCRIPTION
**Pull request by Sadless74**
Russian translation. Previous wrong. Sorry

### CODE REVIEW

**Comment by Sadless74** [comment]
Something wrong on CI
> $ lektor build
> Started build
> ...
> U ru/index.html
>   E ru/index.html (UndefinedError: 'None' has no attribute 'iteritems')
> ...
> U ru/style-guide/index.html
>   E ru/style-guide/index.html (TypeError: expected string or buffer)
> ...
> Error: Build failed with 2 failures.
> Finished build in 0.25 sec
> Started prune
> Finished prune in 0.01 sec
> The command "lektor build" exited with 1.
> Done. Your build exited with 1.

I don't what problem. Need help
